### ISSUE TITLE
profile list in popup menu is missing in "Private Browsing" windows

### ISSUE THREAD

**Issue by bhoppi** [FelisCatus/SwitchyOmega#1163]
And quick rules in popup menu are also not displayed. While the proxy actually works well in the background.
I use FF 55.

SwitchyOmega 2.5.0
Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: wss://push.services.mozilla.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
In Firefox, `localStorage` is separate for private windows so SwitchyOmega cannot read the cached profile list. This can be fixed if we can avoid using `localStorage` and use `browser.storage` instead. Doing so would also fix issues caused by clearing cache, such as #1054.

**Comment by FelisCatus** [comment]
A fix has been committed which works around the issue by using the background page as a bridge to `localStorage`. This should fix the private window issue for now, buying us more time to work on a full migration to `browser.storage`.

**Comment by FelisCatus** [comment]
v2.5.5 released with the fix.

**Comment by Sam0523** [comment]
This issue still appears on SwitchyOmega 2.5.20, Firefox 108.

**Comment by bhoppi** [comment]
> This issue still appears on SwitchyOmega 2.5.20, Firefox 108.

This is an old issue. In newer Firefox versions you can enable "Run in Private Windows" for the extension to solve the issue.

**Comment by Sam0523** [comment]
> > This issue still appears on SwitchyOmega 2.5.20, Firefox 108.
> 
> This is an old issue. In newer Firefox versions you can enable "Run in Private Windows" for the extension to solve the issue.

I have already enabled that option, but the issue still exists.

Reproduce route:
1. Open a new private window. Everything looks fine for now.
2. Open a arbitrary website, open the popup menu of SwitchyOmega, and select "Add condition". 
   You will see the **profile name in the title is missing**, and Profile **drop down menu is empty**.
![image](https://user-images.githubusercontent.com/10058007/210172924-f441030e-2af7-410b-b013-3dc87c01c9dc.png)

3. Open a website which produces "failed resources" hints. Click on the hint, it says "You can add switch conditions for them only when using a Switch Profile." (I am already using a switch profile.)
![image](https://user-images.githubusercontent.com/10058007/210173113-14ef0e3a-c3ed-48fd-a4bb-b6dd43ee4344.png)

4. Click on the "Configure Network Monitor" button, the preference page pops up. Now open SwitchyOmega menu again, all profiles are gone.
![image](https://user-images.githubusercontent.com/10058007/210173355-c0ba086b-38fa-4167-848c-aaa34d04a44a.png)
